# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuitionfee', models.CharField(max_length=10)),
                ('messfee', models.CharField(max_length=10)),
                ('busfee', models.CharField(max_length=10)),
                ('hostelfee', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='busfee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee3', to='newapp.Fees'),
        ),
        migrations.AddField(
            model_name='classes',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Division'),
        ),
        migrations.AddField(
            model_name='classes',
            name='hostelfee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee4', to='newapp.Fees'),
        ),
        migrations.AddField(
            model_name='classes',
            name='messfee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee2', to='newapp.Fees'),
        ),
        migrations.AddField(
            model_name='classes',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Standard'),
        ),
        migrations.AddField(
            model_name='classes',
            name='tuitionfee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee1', to='newapp.Fees'),
        ),
    ]
