# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='busfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fees',
            name='hostelfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fees',
            name='messfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fees',
            name='tuitionfee',
            field=models.IntegerField(default=0),
        ),
    ]
