# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20180806_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feestatus',
            field=models.CharField(choices=[('paid', 'Paid'), ('not Paid', 'Not Paid')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
